### PR TITLE
Add ability to use ssl connection in Server command

### PR DESCRIPTION
**Pull request by VladimirPal**
It's very useful to have ability to run dev server with ssl support, for example if you develop backend for browser extension, browser allow send requests only to https.

### CODE REVIEW

**Comment by VladimirPal** [comment]
@danjac @techniq What do you think about it guys?

**Comment by techniq** [comment]
Looks good to me but @smurfix has taken over maintaining this project (I haven't used Flask for over a year now).  Hopefully he can get this merged (and fix the failing Python 3.3 tests on Travis).

**Comment by VladimirPal** [comment]
@smurfix What's your thoughts?

**Comment by VladimirPal** [comment]
@smurfix I can see that you haven't time or interest to maintain the project. I am happy to continue this project, can you transfer it it to me?

**Comment by smurfix** [comment]
Interest, yes; time, not so much at the moment.

I have added you to the Collaborators list, so you can push changes yourself.

**Comment by VladimirPal** [comment]
@smurfix Thank you. Soon i'll find some time to spend it for the project.

**Comment by jeffwidman** [comment]
@VladimirPal Since you have commit rights to this repo, is there any reason you never merged this?

**Pull request merged**
